# Site settings
title: Hyunwoo Joo
email: stevepaulljobs@gmail.com
description: >-
  Machine Learning Engineer & Researcher
  Sharing insights on AI, 3D Vision, and MLOps
baseurl: ""
url: "https://james-joobs.github.io"
github_username: james-joobs

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  notes:
    output: true
    permalink: /notes/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hyunwoo Joo"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

# Navigation
header_pages:
  - _pages/about.md
  - _pages/posts.md
  - _pages/projects.md
  - _pages/notes.md

# Include
include:
  - _pages

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/
  - README.md

# Minima settings
minima:
  social_links:
    github: james-joobs
    linkedin: hyunwoo-joo-a501b27b
